


server:
  port: 8090
spring:
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-classname: ${db.driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: identity-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    consumer:
      bootstrap-servers: 172.26.0.6:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: searchesId
  config:
    import: configserver:http://localhost:8086/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DB_HOST:localhost}:8761/eureka/
    enabled: true
